# Generated by Django 4.1.5 on 2023-02-02 22:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("votes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Retro",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(default="joining", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("feeling", models.CharField(max_length=10)),
                ("x", models.IntegerField(default=0)),
                ("y", models.IntegerField(default=0)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.cluster",
                    ),
                ),
                (
                    "retro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.retro"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("votes", models.JSONField()),
                (
                    "retro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.retro"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cluster",
            name="retro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.retro"
            ),
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "retro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.retro"
                    ),
                ),
            ],
        ),
    ]
